Modelica_LinearSystems2/UsersGuide.mo
Modelica_LinearSystems2/package.mo
README.md

Adapted for new MSL version.
I believe at least the following should also be handled: #64
The some other open issues could also be handled.

New version

---

Modelica_LinearSystems2/Controller/Examples/Components/AccelerationLimiter.mo
Modelica_LinearSystems2/DiscreteZerosAndPoles.mo
Modelica_LinearSystems2/Internal/Streams/readMatrixInternal.mo
Modelica_LinearSystems2/Internal/Streams/readMatrixOnFileSize.mo
Modelica_LinearSystems2/Math/Matrices/Internal/solve2rSym_C.mo
Modelica_LinearSystems2/Math/Matrices/Internal/solveSymRight_C.mo
Modelica_LinearSystems2/Math/Matrices/Internal/symMatMul_C.mo
Modelica_LinearSystems2/Math/Matrices/LU.mo
Modelica_LinearSystems2/ZerosAndPoles.mo

Corrected a number of minor issues with annotations for Modelica_LinearSystems2.
It would be good to have it merged before https://github.com/modelica/Modelica_LinearSystems2/pull/72
because that gives a corrected pre-MSL 4 version.
Any potential merge conflict should be trivial.

Fix annotations

---

Modelica_LinearSystems2/DiscreteStateSpace.mo
Modelica_LinearSystems2/DiscreteTransferFunction.mo
Modelica_LinearSystems2/DiscreteZerosAndPoles.mo
Modelica_LinearSystems2/Internal/StateSpace2.mo
Modelica_LinearSystems2/Internal/StateSpaceR.mo
Modelica_LinearSystems2/StateSpace.mo
Modelica_LinearSystems2/TransferFunction.mo
Modelica_LinearSystems2/ZerosAndPoles.mo

Fix false inheritance of operators and operator records

---

Modelica_LinearSystems2/Controller/Examples/Components/InverseDoublePendulum.mo
Modelica_LinearSystems2/Controller/Examples/Components/InverseDoublePendulum2.mo
Modelica_LinearSystems2/Controller/Examples/Components/InverseDoublePendulum3.mo
Modelica_LinearSystems2/Controller/Examples/MixingUnit.mo
Modelica_LinearSystems2/Utilities/Plants/DoublePendulumInverse.mo

(except in WorkInProgress classes)

Omit mentioning of Modelica_Controller library in documentation

---

Modelica_LinearSystems2/DiscreteStateSpace.mo
Modelica_LinearSystems2/DiscreteTransferFunction.mo
Modelica_LinearSystems2/DiscreteZerosAndPoles.mo
Modelica_LinearSystems2/Math/Polynomial.mo
Modelica_LinearSystems2/StateSpace.mo
Modelica_LinearSystems2/TransferFunction.mo
Modelica_LinearSystems2/Utilities/Import/linearize.mo
Modelica_LinearSystems2/Utilities/Import/linearize2.mo
Modelica_LinearSystems2/Utilities/Import/rootLocusOfModel.mo
Modelica_LinearSystems2/Utilities/Plot/Internal/convertToDymolaMarker.mo
Modelica_LinearSystems2/Utilities/Plot/Internal/convertToDymolaPattern.mo
Modelica_LinearSystems2/Utilities/Plot/diagram.mo
Modelica_LinearSystems2/Utilities/Plot/diagramVector.mo
Modelica_LinearSystems2/Utilities/Plot/parameterizedCurves.mo
Modelica_LinearSystems2/WorkInProgress/DiscreteZerosAndPoles.mo
Modelica_LinearSystems2/WorkInProgress/RootLocusOld.mo
Modelica_LinearSystems2/WorkInProgress/plotEigenvalues.mo
Modelica_LinearSystems2/WorkInProgress/plotRootLoci.mo
Modelica_LinearSystems2/WorkInProgress/plotRootLociNoLoop.mo
Modelica_LinearSystems2/ZerosAndPoles.mo
Modelica_LinearSystems2/package.mo

Use functions from DymolaCommands

---

Modelica_LinearSystems2/Math/Polynomial.mo

Add no new features for the next bug-fix release version.

Revert addition of function for 2nd derivation of polynomial

---

Modelica_LinearSystems2/StateSpace.mo

... in case of non-existing input file

readSystemDimension: Set emergency vector sizes

---

Modelica_LinearSystems2/Controller/StateSpace.mo
Modelica_LinearSystems2/Controller/Templates/Internal/ObserverTemplate.mo

cf. 02c28639ba88743ea8f86a667f1ef307207eed2b

Improve declaration of  StateSpace parameter

---

Modelica_LinearSystems2/Internal/frequencyResponseGain.mo

Fix false documentation

---

Modelica_LinearSystems2/Controller/Interfaces/PartialBlockIcon.mo
Modelica_LinearSystems2/Controller/Internal/Add.mo
Modelica_LinearSystems2/Internal/PartialAnalyzeFunction.mo
Modelica_LinearSystems2/Internal/frequencyResponse.mo
Modelica_LinearSystems2/Utilities/Import/linearize2.mo
Modelica_LinearSystems2/Utilities/Import/rootLocusOfModel.mo
Modelica_LinearSystems2/Utilities/Plot/rootLocusOfModel.mo

In particular: 'enable' and 'visible'

Resolve dependency on unknown variables in annotations

---

Modelica_LinearSystems2/Controller/Examples/Components/DoublePendulum2.mo
Modelica_LinearSystems2/Controller/Interfaces/PartialBlockIcon.mo
Modelica_LinearSystems2/DiscreteStateSpace.mo
Modelica_LinearSystems2/DiscreteZerosAndPoles.mo
Modelica_LinearSystems2/Internal/frequencyResponsePlot.mo
Modelica_LinearSystems2/Internal/from_Hz.mo
Modelica_LinearSystems2/Internal/to_Hz.mo
Modelica_LinearSystems2/Math/Matrices/package.mo
Modelica_LinearSystems2/Math/Matrices/toUpperHessenberg.mo
Modelica_LinearSystems2/Math/Vectors/length.mo
Modelica_LinearSystems2/Math/Vectors/package.mo
Modelica_LinearSystems2/StateSpace.mo
Modelica_LinearSystems2/TransferFunction.mo
Modelica_LinearSystems2/WorkInProgress/Controller/LimIntegratorReset.mo
Modelica_LinearSystems2/WorkInProgress/DiscreteStateSpace.mo
Modelica_LinearSystems2/WorkInProgress/DiscreteTransferFunction.mo
Modelica_LinearSystems2/WorkInProgress/DiscreteZerosAndPoles.mo
Modelica_LinearSystems2/WorkInProgress/StateSpace/Conversion/toTransferFunction.mo
Modelica_LinearSystems2/WorkInProgress/StateSpace/Design/UKF.mo
Modelica_LinearSystems2/ZerosAndPoles.mo

Use lower case scheme of URI

---

Modelica_LinearSystems2/Controller/LimPID.mo
Modelica_LinearSystems2/Controller/PID.mo
Modelica_LinearSystems2/Math/Matrices/householderReflexion.mo
Modelica_LinearSystems2/Math/Matrices/householderSimilarityTransformation.mo

Fix broken links

---

Modelica_LinearSystems2/ModelAnalysis.mo
Modelica_LinearSystems2/StateSpace.mo

Add full path of report file on output

---

LinearSystems2TestConversion3.mo
Modelica_LinearSystems2/Math/Polynomial.mo
Modelica_LinearSystems2/Resources/Scripts/Conversion/ConvertLinearSystems2_from_2.4.0.mos
Modelica_LinearSystems2/UsersGuide.mo

Fix wrong calculation of polynomial's degree

---

Modelica_LinearSystems2/Resources/Scripts/Conversion/ConvertLinearSystems2_from_2.4.0.mos
ObsoleteLinearSystems2.mo

Move obsolete internal functions into proper package

---

Modelica_LinearSystems2/Math/Polynomial.mo
Modelica_LinearSystems2/Resources/Scripts/Conversion/ConvertLinearSystems2_from_2.4.0.mos
Modelica_LinearSystems2/UsersGuide.mo

Move internal polynomial functions into Internal package

---

Modelica_LinearSystems2/ComplexMathAdds/frequency.mo
Modelica_LinearSystems2/Internal/Eigenvalue.mo

See also https://github.com/modelica/ModelicaStandardLibrary/pull/4358

Use sqrt(x) instead of x^0.5

---

Modelica_LinearSystems2/ZerosAndPoles.mo

Don't set outermost parentheses for a "one-term" denominator

---

Modelica_LinearSystems2/StateSpace.mo

Return empty matrices when system has no states

---

Modelica_LinearSystems2/Controllers/Internal/random.mo

… and slightly change the documentation.
Close #175

Fix broken link to BSD 3-Clause License
